name: 'CI - Verificação de Qualidade (HTML/CSS)'

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: 🚀 Checkout do Código
        uses: actions/checkout@v4

      # ==========================================================
      # PASSO 1: LINTING APENAS PARA HTML
      # ==========================================================
      - name: 'PASSO 1: Validar HTML'
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_HTML: true
          DEFAULT_BRANCH: main

      # ==========================================================
      # PASSO 2: LINTING APENAS PARA CSS
      # ==========================================================
      - name: 'PASSO 2: Validar CSS'
        uses: github/super-linter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: true
          VALIDATE_CSS: true
          DEFAULT_BRANCH: main

      - name: 'Exibir mensagem final de sucesso'
        # Este passo só é executado se ambos os passos (HTML e CSS) passarem
        if: ${{ success() }}
        run: |
          echo '🎉 Linting de HTML e CSS concluído com sucesso!'
          echo 'Seu código está validado e pronto para o Build!'